FROM python:3.9

RUN mkdir /app
WORKDIR /app
COPY . /app

RUN pip3 install install -y xmltodict && \
    pip3 install install -y logging && \
    pip3 install install -y statistics && \
    pip3 install install -y requests && \
    pip3 install install -y datetime && \
    pip3 install install -y math

RUN pip3 install Flask==3.0.2
RUN pip3 install pytest==8.0.0

ENTRYPOINT [ "python" ]
CMD [ "iss_tracker.py" ]